language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - pypy3
install:
  - pip install -e .
  - pip install -r test-requirements.txt
  - pip install tornado
script: nosetests
after_success:
  - coveralls
deploy:
  provider: pypi
  user: sprockets
  password:
    secure: qzSC7nsNS1rnDKgiZe2GiojMznf35GLzUeqlf5HESYiKDIlXLIpdxS1Ii9G+afnJH1cGT9dheDUvlRzwZ3eDsZHbVYjKtj/uvy8j4x8H+N66Zvm1AMdGvF4sDCUo01DdbsSe7Xh77VY3kV0AgHb8UZuXOgXcdN0kYJjfWuUWTl0=
  distributions: "sdist bdist_wheel"
  on:
    python: 3.6
    tags: true
    all_branches: true
